baseURL = "https://Tiifeuille.github.io/my-game-archive/"
languageCode = "en-us"
title = "亵欲纳间"

timeout = "120s"

defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 6


