# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "favicon.ico"

[footer]
since = 2020
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸ“¼"
subtitle = "Tiffanyçš„å„ç±»ç§è´§å­˜æ¡£ç‚¹"

[sidebar.avatar]
    enabled = true
    local = true
    src = "hoshino1.jpg"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = "img/hoshino1.png"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
    enabled = true
    provider = "giscus"

[comments.giscus]
    repo = "Tiifeuille/my-game-archive"  
    repoID = "R_kgDOQoZfgw"
    category = "Announcements" 
    categoryID = "DIC_kwDOQoZfg84Czxqd" 
    mapping = "pathname"
    reactionsEnabled = 1
    emitMetadata = 0
    lightTheme = "light"
    darkTheme = "dark_dimmed" 